### ISSUE TITLE
Compatibility with the Flatpak version of KeepassXC

### ISSUE THREAD

**Issue by Technohacker** [Frederick888/git-credential-keepassxc#25]
The flatpak version seems to move the path
`$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer`
to
`$XDG_RUNTIME_DIR/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer`

Perhaps the path to the named pipe could be set in a config file for when it's required?

**Comment by Frederick888** [comment]
Yes I can confirm flatpak patches KPXC to change the socket path: https://github.com/flathub/org.keepassxc.KeePassXC/blob/master/patch/keepassxc/0004-Flatpak-Support-sandboxed-attachment-opening.patch

But instead of adding an attribute to the configuration file, how about exploring the option of using an environment variable?

If you have a look at the current [command line options](https://github.com/Frederick888/git-credential-keepassxc/blob/master/src/cli.yml), there are quite a few that actually make sense to be persisted somewhere. However as it stands atm, the configuration file is solely used to store credentials. So jumping too quickly onto changing its contents sounds like opening a can of worms to me. In the future if there are needs, I'd rather aim for a more generic solution.

**Comment by Technohacker** [comment]
Yeah I just wanted to see if the path could be configurable in some way, implementation can be as suitable :)

**Comment by Frederick888** [comment]
@Technohacker Yes, and it shouldn't be too difficult to write a bash wrapper to give it a default value. Though that'll mess with the caller verification unless bash has already been added, so still I think I'll add an environment variable as sandbox packages (snap, flatpak, etc) seem to often have non-standard socket paths.

**Comment by Technohacker** [comment]
That being said, I noticed Git's credential helper config does allow passing CLI arguments and I've got it working on my setup, just had to set it as `keepassxc <arguments here>`, so this'll do for now :D
