### ISSUE TITLE
Bug/Feature request: Allow URL to be optional

### ISSUE THREAD

**Issue by stdedos** [Frederick888/git-credential-keepassxc#32]
While URL makes sense for the original purpose of the program (i.e. `git-credential-...`), it makes it complicated to fetch tokens that are not associated with a URL (i.e., simple [key, value] pairs)

Maybe you can allow:
```console
$  printf 'username=%s\n' "SUPER_SECRET" | git-credential-keepassxc get
Feb 10 09:27:54.103 ERRO Protocol and host are both required when URL is not provided, Caused by: N/A
```

However, explicit
```console
$ printf 'url=\nusername=%s\n' "SUPER_SECRET" | git-credential-keepassxc get
Feb 10 09:28:36.692 ERRO Request get-logins failed, No URL provided (code: NoUrlProvided), Caused by: N/A
```

should be a way to work around that?

I am fine if you'd like to hide this "protocol deviation" by introducing e.g. a `--no-url-is-okay` argument flag

**Comment by Frederick888** [comment]
Unless I overlooked something, URL is required by the protocol https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-protocol.md#get-logins.

**Comment by stdedos** [comment]
Sadly, I think you are right 😦

**Comment by TLATER** [comment]
So, since I'm also just trying to use this to get autotyping to work on wayland (through a script launched by my WM that calls `wdotool`), there's a pretty easy workaround.

If you just add an additional URL with a custom protocol to the list of URLs, you can use e.g.:

```
printf "url=title://%s" "$WINDOW_TITLE" | git-credential-keepassxc get
```

I'm sure this is obvious to some, but I wanted to spell it out since it makes this tool *much* more versatile.
