### ISSUE TITLE
Infinite loop when respons is a multiple of 128 bytes

### ISSUE THREAD

**Issue by pitdicker** [Frederick888/git-credential-keepassxc#35]
Not sure how rare this is to trigger, but it happened on one PC consistently when combined with KeePassNatMsg. Println-debugging showed `read_to_end` doesn't return when the response is a multiple of 128 bytes. Code:
https://github.com/Frederick888/git-credential-keepassxc/blob/v0.8.2/src/utils.rs#L247:L252

Usually the next `.read()` should return `0`, but apparently somewhere in the stack this doesn't work.

**Comment by Frederick888** [comment]
I assume we are talking about Windows here?

I'm afraid I haven't got a proper local Windows environment and I don't use
KeePass 2 / KeePassNatMsg, so I'm not sure when / if I'll be able to look into
this problem myself. Though in the meanwhile, I added some debug logs [1] in
`read_to_end` and I'm wondering if you can try it out [2]?

[1] https://github.com/Frederick888/git-credential-keepassxc/blob/dd3b0b950b9f6e86e0b4f3c59163df6ac64ae057/src/utils.rs#L266-L272
[2] https://github.com/Frederick888/git-credential-keepassxc/wiki/Troubleshooting#debug-logs

**Comment by pitdicker** [comment]
Yes, this is about Windows, no problems for me on Linux.
With the debug logs it hangs reliably after receiving 4 times 128 bytes.
I'll try to work on it for a bit.

**Comment by Frederick888** [comment]
I think I probably know the reason then.

Since these network-like streams haven't got an 'end' unless they are
closed, instead of returning 0 or error, read() just blocks when there's
no data.

This actually also impacts Linux. I tried setting BUF_SIZE to 1 [1] and
it started to block every time.

As a workaround, I added a timeout on these streams in [2] and confirmed
this fixed the issue on Linux using KeePassXC. The timeout is 200ms
which I think is appropriate for local streams, but it'd be nice if you
can test it out as well.

PS: It'll be even better if we can use logic like [3] to detect JSON
boundaries here, but it gets tricky due to these streams' duplex nature.
KeePassXC Browser can handle this since it's a long-running process.
Anyway, the workaround looks good enough to me atm.

[1] https://github.com/Frederick888/git-credential-keepassxc/blob/dd3b0b950b9f6e86e0b4f3c59163df6ac64ae057/src/utils.rs#L262
[2] https://github.com/Frederick888/git-credential-keepassxc/tree/read-timeout
[3] https://github.com/Frederick888/git-credential-keepassxc/blob/dd3b0b950b9f6e86e0b4f3c59163df6ac64ae057/src/utils.rs#L283-L327

**Comment by pitdicker** [comment]
Sorry for the slow reply! I learned a few things, but put off writing it down for too long.

Named pipes on Windows appearently can not only be used as just a byte stream, but also in message mode. If the read buffer is not large enough, it will write part of the message and return `ERROR_MORE_DATA` ([link](https://docs.microsoft.com/en-us/windows/win32/ipc/transactions-on-named-pipes)). But [KeePassNatMsg](https://github.com/smorks/keepassnatmsg/blob/v2.0.14/KeePassNatMsg/Protocol/Listener/NamedPipeListener.cs#L90) explicitly sets up the pipe in byte mode. And [KeePassXC](https://github.com/keepassxreboot/keepassxc/blob/2.6.6/src/browser/BrowserHost.cpp) uses QT's [`QlocalSocket`](https://doc.qt.io/qt-5/qlocalsocket.html), which on first look only supports byte mode.

The difference between git-credential-helper and the browser proxies is the buffer size of 1024*1024 bytes ([KeePassXC](https://github.com/keepassxreboot/keepassxc/blob/2.6.6/src/proxy/NativeMessagingProxy.cpp#L92), [keepassxc-proxy-rust](https://github.com/varjolintu/keepassxc-proxy-rust/blob/master/src/main.rs#L14), [KeePassNatMsg](https://github.com/smorks/keepassnatmsg-proxy/blob/v0.0.8/ProxyBase.cs#L10).

Your solution of using a timeout to detect the end of a message makes the most sense to me, otherwise there is always some message size that gives problems. Would it be a good idea to also use the same buffer size?

**Comment by Frederick888** [comment]
TIL Windows named pipes have 2 modes! Luckily the client I use supports
only bytes mode [1], so we are not wrong from the get-go, phew!

And I can certainly bump up the buffer size, but as you mentioned, that
may only make the issue happen less often (and more difficult to hunt
down!). So may I know if `read-timeout` branch already solves your issue,
i.e. you can see `Received 128 bytes: xxxx` and only `128 bytes` in
debug logs?

[1] https://github.com/blackbeam/named_pipe/blob/08b0f362a282803c31a4591f09c59e5c697f73c0/src/lib.rs#L188

**Comment by Frederick888** [comment]
By the way if you no longer have the KeePass record that you used to
produce the issue, you can also set `BUF_SIZE` [1] to `1` to see if it
hangs.

[1] https://github.com/Frederick888/git-credential-keepassxc/blob/970578ea67a05f44ec5b603ec656f9ca925f655b/src/utils.rs#L267

**Comment by pitdicker** [comment]
Just did a fresh test, the `read-timeout` branch works perfectly!

**Comment by Frederick888** [comment]
Music to my ears :) I'll try getting a release out by this weekend.

I'll also bump the buffer size to 2048 or something, which is usually enough if you get 1 or 2 records per request. The buffer is atm on stack so being a tad frugal here :P

**Comment by Frederick888** [comment]
Realised that I had to removed the timeout and take the larger buffer
approach since the timeout breaks credential retrieval when the record
requires user approval (by clicking on Allow Selected in a pop-up
dialogue in KPXC).

v0.9.1 coming... lol
